### ISSUE TITLE
Bit Coins Transaction error

### ISSUE THREAD

**Issue by AndyKD** [ValleZ/Paper-Wallet#28]
64: non-mandatory-script-verify-flag (Non-canonical signature: S value is unnecessarily high). Code:-26

Pls help

**Comment by ValleZ** [comment]
Does it work for you? https://github.com/ValleZ/Paper-Wallet/commit/b29c13cdf1aa6f33be2f1680f7bda0628b6f1174

**Comment by AndyKD** [comment]
hi @ValleZ I changed into code, its working but sometime while I try to combine more unspent counts into single transaction hex, it gives dusty transaction error. Any Idea?

**Comment by ValleZ** [comment]
Do you use hex-encoded transactions as input? If the error is "Unable to decode given transaction" then it's probably because input transaction has unsupported format like multisig or pay to script which are likely nt supported, see "decodeUnspentOutputsInfoTask". You can debug if baseTx is actually non-null and looks correct you can disable this check:
`if (!Arrays.equals(rawTxReconstructed, rawTx)) {
                                    throw new IllegalArgumentException("Unable to decode given transaction");
                                }`

**Comment by ValleZ** [comment]
ah, wait. dusty? Probably it's because tx is too small - bitcoin network rejects too small tx to protect against spam. try to increase fee.

**Comment by ValleZ** [comment]
can you share amounts + fee you use?

**Comment by AndyKD** [comment]
I was using 0.0001 or 0.0001

**Comment by ValleZ** [comment]
Ah, yes, it can happen when outputs are less than 0.1.
