### ISSUE TITLE
Don't let generate password-protected SegWit keys

### ISSUE THREAD

**Issue by ValleZ** [ValleZ/Paper-Wallet#52]
BIP38 is ambiguous spec for new addresses, what results in multiple valid implementations, including ones which cannot decode it at all because of the last verification step.

App should allow to decode all possible BIP38 keys.

**Comment by ValleZ** [comment]
Other, better(?) option is to use legacy addresses for hash verification only. This will let more other apps decode (at least legacy address)

https://github.com/BlueWallet/BlueWallet/issues/4156#issuecomment-961550726

**Comment by junderw** [comment]
Be careful when changing the way hash verification works.

If you update to conform to the BIP and only use legacy, then make sure:

- encrypt -> only use legacy
- decrypt -> check both legacy and bech32 (and any other address type you have used in the past for hash verification)

Otherwise, a user who generated a key using bech32 for hash verification can not recover using your new wallet version.

**Comment by ValleZ** [comment]
I agree, thank you!
